// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvoRio25YWJcF7-4nQ1AXj6KIj8n67C84',
    appId: '1:246050780513:web:1905b59e6e03f16ad78120',
    messagingSenderId: '246050780513',
    projectId: 'flutter-away-cde1f',
    authDomain: 'flutter-away-cde1f.firebaseapp.com',
    databaseURL: 'https://flutter-away-cde1f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-away-cde1f.appspot.com',
    measurementId: 'G-7249N0W0JK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHMqxkwh305jRsvB2zkOoyGLWzfaHFSoM',
    appId: '1:246050780513:android:a46267bc522076d0d78120',
    messagingSenderId: '246050780513',
    projectId: 'flutter-away-cde1f',
    databaseURL: 'https://flutter-away-cde1f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-away-cde1f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4OKP_yD_RGnwW_F8n2X1NmsTey-Ejevk',
    appId: '1:246050780513:ios:5a3e584f6ad9275cd78120',
    messagingSenderId: '246050780513',
    projectId: 'flutter-away-cde1f',
    databaseURL: 'https://flutter-away-cde1f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-away-cde1f.appspot.com',
    iosBundleId: 'com.example.salonBookingFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4OKP_yD_RGnwW_F8n2X1NmsTey-Ejevk',
    appId: '1:246050780513:ios:8d7e88bbab361155d78120',
    messagingSenderId: '246050780513',
    projectId: 'flutter-away-cde1f',
    databaseURL: 'https://flutter-away-cde1f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-away-cde1f.appspot.com',
    iosBundleId: 'com.example.salonBookingFlutterApp.RunnerTests',
  );
}
